### ISSUE TITLE
Umlaute äöü

### ISSUE THREAD

**Issue by ghost** [GZidar/CorePDF#13]
Hello GZidar,

thank you for you library, I like it very much.

I noticed that the library has problems with Umlaute (like äöüéè and so on).
I'm working in a Winsows 10 Environment.
Is it possible to attach my own fonts?

Kind regards
Fabian

**Comment by GZidar** [comment]
Hi @fabian-protonx, thanks for your feedback. The project started as a kind of thought experiment and evolved from there but it is still quite bare bones. At the moment it only has data for the basic fonts that are built into the PDF standard. But I think there is a way to add your own fonts provided you know the font metrics. You can edit the font.cs file to add whatever font you like and create a PR for that when you are happy with how it works. However to use a different font you will also have to embed the actual font file and that isn't something that I have done yet. If you'd like to investigate how to include fonts into the PDF (I expect that they need only be embedded into the file much like images) then I'd love to include your work into the library.

**Comment by GZidar** [comment]
Hi @fabian-protonx, I have now added the ability to embed TrueType fonts into the PDF document and have updated the sample code in the readme to show how this is done. There is a bit of fiddling around needed to get the magic numbers for the character widths and other required font metrics (CapHeight, Weight, StemV, ItalicAngle, etc.) but if you have those the library now supports adding extra fonts beyond those included by default.

Please let me know if you run into any problems, and sorry this feature took so long

**Comment by ghost** [comment]
Hi Goran

thank you for your infos.

I know, its not that easy to work with fonts,
but I'm shure you have done a great job.

At the moment I'm in the middle of a big project,
but after that I'll have a look at your library.

Thank you for your effort and keep on coding

Fabian




Am .03.2018, 01:11 Uhr, schrieb Goran Zidar <notifications@github.com>:

>
> Hi @fabian-protonx, I have now added the ability to embed TrueType fonts  
> into the PDF document and have updated the sample code in the readme to  
> >show how this is done. There is a bit of fiddling around needed to get  
> the magic numbers for the character widths and other required font  
> metrics >(CapHeight, Weight, StemV, ItalicAngle, etc.) but if you have  
> those the library now supports adding extra fonts beyond those included  
> by default.
>
> Please let me know if you run into any problems, and sorry this feature  
> took so long
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Erstellt mit Operas E-Mail-Modul: http://www.opera.com/mail/
