### ISSUE TITLE
PDF not working after deployment in production

### ISSUE THREAD

**Issue by srikanthkataram** [GZidar/CorePDF#21]
We have introduced images in pdf and working locally absolutely fine but it does not after we deploy to our production environment. We are using file version: 0.1.0.0 and product version 0.1.0.

**Comment by GZidar** [comment]
Not sure why that would be the case, but perhaps you could try using version 0.4.0 it is flagged as beta only because it has a dependency on the beta version of ImageSharp. See if the latest version addresses the problem. If not then perhaps the issue is a path permission one.
