### ISSUE TITLE
Embeding fonts

### ISSUE THREAD

**Issue by lowrylp** [GZidar/CorePDF#24]
Hi there.
I am using CorePDF version 0.4.0-beta.
You example for embedding font is pretty simple but I have a couple of questions.
The example seems to be for TTF's.  Can OTF also be embedded?
There is a lot of metadata required for the embedding.  If I get a free font what is the
best way to discover that information?

I want to embed a free Titillium font.

Thanks.

Larry

**Comment by GZidar** [comment]
Hi Larry.

What I found was the simplest, was to use the font in a word document, and then create a PDF from that. Then you can open the resulting PDF and it should have the numbers needed to add the metrics. There must be a way to read this data from the font itself but I haven't the opportunity to spend any time doing that. I believe that OTF and TTF should be pretty much equivalent in terms of ability to embed them. 

I hope that helps, best of luck to you :-)
