### ISSUE TITLE
PDF size for embedded image

### ISSUE THREAD

**Issue by callsoft** [GZidar/CorePDF#25]
I'm trying to convert a tif file that is 80k to a pdf and while the conversion to pdf works, it is 25MB in size.  Is there a way to enable compression or reduce the DPI?

Here's the code I'm using:

```c#
        public byte[] ImageToPdf(byte[] image)
        {
            var d = new CorePDF.Document();

            d.Images = new List<CorePDF.Embeds.ImageFile>
            {
                new CorePDF.Embeds.ImageFile
                {
                    FileData = image,
                    Name = "Image"
                }
            };

            d.Pages.Add(new CorePDF.Pages.Page
            {

                PageSize = Paper.PAGEA3PORTRAIT,
                Contents = new List<Content>() {
                new CorePDF.Contents.Image
                {
                    ImageName = "Image",
                    PosX = 50,
                    PosY = 100,
                    ScaleFactor = 0.25m
                },

                }
            });

            using (var stream = new MemoryStream())
            {
                d.Publish(stream);
                return stream.ToArray();
            }
        }
```

**Comment by GZidar** [comment]
Image compression isn't something that has been implemented in this utility (but it is a good idea if you want to add it :-) ). One suggestion would be to use the ImageSharp library (for example) to compress the image before you add it to the document. 

https://github.com/SixLabors/ImageSharp

**Comment by callsoft** [comment]
I'll check it out thanks.  But just to confirm (I'm not an expert on pdfs or image processing), even though the image file is already small (80k), you are saying it is normal for the PDF size to then be 25MB if the image is not first compressed--yes?  It just seems strange that the pdf conversion process would blow it up like that.

**Comment by GZidar** [comment]
I am not sure why the TIFF would grow from 80k to 25MB but the way images are saved in the pdf is to take the rgb bytes from the image and write them to the document so at most I would expect the image to grow (maybe) by 3x assuming that the TIFF is not itself compressed. If the TIFF is compressed then perhaps the act of uncompressing it to get the raw bytes is what has caused it to grow in such a way. Is the image large (in terms of the number of pixels)?

**Comment by callsoft** [comment]
Yes it's 2544x3394 @ 300 dpi.

**Comment by GZidar** [comment]
Ok, so that makes sense then. That comes to 8,634,336 bytes (approx. 8MB) per color x 3 (for RGB) is approx. 24MB. You could try setting the CompressContent property in the document (in your sample code that would be d.CompressContent) to true and see if that helps keep the size down. But I can't recall if that was implemented for images...

**Comment by callsoft** [comment]
I just tried that--no difference.  I'll try to resize and convert to PNG and see if that makes any difference.  Thanks!

**Comment by callsoft** [comment]
Resizing it to a more dimensions fixed my issue.  I used ImageSharp to resize then added it to the pdf and it came out as expected (< 2MB).

Thanks!
